### ISSUE TITLE
Convert over to CNI from netns

### ISSUE THREAD

**Issue by alexellis** [alexellis/faasd#19]
Convert over to CNI from netns

## Expected Behaviour

This is mentioned in the README, we should use CNI for container networking rather than the nets binary.

## Current Behaviour

netns binary which I believe is unmaintained

## Possible Solution

There's an open PR from @carlosedp, it would make sense for Carlos to apply the same patch here once tested / released.

https://github.com/alexellis/faas-containerd/pull/18

## Context

The README, e2e tests and several blog posts need to be updated to accommodate the change.

**Comment by carlosedp** [comment]
Addressed in #21 and #23

**Comment by alexellis** [comment]
You can put yourself into .DEREK.yml so that you can close issues and PRs. Also, you should add to your commit messages: Closes: #21 Etc
