### ISSUE TITLE
Add "faasd provider" command

### ISSUE THREAD

**Issue by alexellis** [alexellis/faasd#20]
faas and faas-containerd do different jobs but can live as one codebase to reduce overhead. They do have some common concerns such as creating containers/tasks and managing network/IPs with CNI.

## Expected Behaviour

Add "faasd start-provider" command which would run the code from [faas-containerd](https://github.com/alexellis/faas-containerd), perhaps vendoring it, or just copy/pasting it into a new package and archiving the old repo.

I'd imagine a new file in `cmd/` and a new package in `pkg/provider/`

## Current Behaviour

We have two binaries to manage, distribute, test, and update.

## Steps / solution

* Port code into new packages over from faas-containerd into the faasd tree
* Consolidate documentation and systemd unit files
* Remove instructions for installing faas-containerd as a separate binary
* Consolidate any duplicate code
* Publish a new release of faasd
* Archive faas-containerd

**Comment by carlosedp** [comment]
Addressing this issue on PR #23
