### ISSUE TITLE
Build notes: build of containerd fails on jessie due to out of date libseccomp dependency

### ISSUE THREAD

**Issue by vielmetti** [alexellis/faasd#8]
On a whim, tried to build this under a `jessie` based Raspberry Pi system, and got a build failure with the error that the minimum required version of libseccomp is v2.2.0 and jessie only provides 2.1.1.

Not readily possible to fix, and it's time to upgrade that system in any case, so this is just a word of note to anyone building this that there's that dependency.

**Comment by alexellis** [comment]
Thanks for the note, I'd encourage all users to employ a new SD card with the latest version of Raspbian.
